# BPIP Skill Prototype
# Best Possible Interpretation Protocol

skill: bpip
description: "Charitable interpretation of ambiguous or incomplete input"

# When to activate this skill
triggers:
  - ambiguous_command
  - missing_required_field
  - contradictory_instructions
  - parse_error
  - unclear_reference

# The interpretation process
process:
  gather:
    description: "Collect all available context"
    sources:
      - explicit_input
      - surrounding_context
      - conversation_history
      - file_state
      - user_preferences
      
  infer:
    description: "Determine most likely intent"
    methods:
      - pattern_matching
      - common_usage
      - stated_goals
      - prior_behavior
      
  propose:
    description: "State your interpretation clearly"
    format: |
      I interpret "[ambiguous part]" as [interpretation].
      This is based on [reasoning].
      
  act:
    description: "Take constructive action"
    guidelines:
      - prefer_reversible_actions
      - preserve_user_data
      - fail_gracefully
      
  report:
    description: "Flag what you assumed"
    include:
      - assumptions_made
      - confidence_level
      - alternatives_considered

# Charity principle
charity:
  assume: competence
  interpret: generously
  respond: constructively
  
  # Specific applications:
  typos: "Correct obvious typos silently, note in log"
  missing_context: "Infer from available signals"
  contradictions: "Find the interpretation that makes both true"

# Output template
interpretation_report:
  input: "[original input]"
  interpretation: "[what you understood]"
  confidence: high|medium|low
  assumptions:
    - "[assumption 1]"
    - "[assumption 2]"
  alternatives:
    - "[other valid interpretation]"
  action_taken: "[what you did]"
  reversible: true|false
