# 🎯📝 THOUGHTFUL-COMMITMENT
#
# "Commits should tell the story of why, not just what."
#
# A SHOWCASE FOR SKILL COMPOSABILITY
# This skill composes cursor-mirror + git + shell to create something new.
# It demonstrates how MOOLLM skills are building blocks, not silos.

skill:
  name: thoughtful-commitment
  version: 1.0.0
  
  emoji: "🎯📝"
  tagline: "Commits that remember why"
  
  description: |
    Transform mechanical "updated file" commits into narrative records
    that capture the full context: what the user asked, what the LLM
    was thinking, and why the changes matter.
    
    **This skill is a composition of cursor-mirror + git + shell.**
    It showcases how MOOLLM skills combine like LEGO bricks.

# COMPOSABILITY — Skills as Building Blocks

composability:
  principle: "Skills compose. thoughtful-commitment doesn't reinvent introspection — it uses cursor-mirror."
  
  composed_from:
    cursor-mirror:
      role: "Reflective introspection engine"
      what_it_provides:
        - "Chat history (all messages, thinking, tool calls)"
        - "SQLite database access (direct queries)"
        - "Transcript files (plaintext, greppable)"
        - "Thinking blocks (LLM reasoning)"
        - "Tool call patterns (what actions were taken)"
        - "Context assembly (what files were gathered)"
        - "MCP server tracing"
        - "Activity timelines with timestamps"
      commands_used:
        - "timeline <composer>     # Full event sequence"
        - "thinking <composer>     # Reasoning blocks"
        - "tools <composer>        # Tool call history"
        - "analyze <composer>      # Session statistics"
        - "tgrep <pattern>         # Search transcripts"
        - "agent-transcript <id>   # Raw plaintext"
        - "tail --limit N          # Recent messages"
        - "tree                    # Navigate workspaces"
        - "status                  # Health dashboard"
        - "sql --db <ref> 'query'  # Direct SQL"
    
    git:
      role: "Version control substrate"
      what_it_provides:
        - "Commit history"
        - "File diffs"
        - "Blame annotations"
        - "Branch topology"
      commands_used:
        - "git status / diff / log"
        - "git add / commit / push"
        - "git show / blame"
        - "git log --numstat"
    
    shell:
      role: "Data processing pipeline"
      what_it_provides:
        - "Text processing (grep, awk, sed, sort, uniq)"
        - "Metrics extraction (wc, cut)"
        - "Python one-liners for complex analysis"
      patterns_used:
        - "grep -c pattern file           # Count matches"
        - "sort | uniq -c | sort -rn      # Frequency histogram"
        - "awk '{sum+=$1} END{print sum}' # Aggregation"
        - "python3 -c 'import json...'    # JSON processing"

  how_composition_works: |
    1. cursor-mirror provides RAW DATA (transcripts, databases, events)
    2. shell commands TRANSFORM data (count, filter, aggregate)
    3. git provides VERSION CONTEXT (commits, diffs, history)
    4. thoughtful-commitment SYNTHESIZES into narrative commits
    
    Each skill does one thing well. Composition creates new capabilities.

# INTERFACE

tier: 2
allowed_tools:
  - read_file
  - write_file
  - list_dir
  - run_terminal_cmd
  - grep

protocol: THOUGHTFUL-COMMITMENT

related:
  - cursor-mirror      # Primary composition partner — introspection engine
  - session-log        # Where narrative lives
  - plain-text         # Why text matters
  - yaml-jazz          # Comments as meaning

workflow:
  description: "Catalog → Identify → Commit"
  steps:
    - "cursor-mirror chat-catalog @1  → numbered topic outline"
    - "User: 'Write commit for sections 11 and 14'"
    - "thoughtful-commitment COMMIT → narrative commit message"
    - "Commit references catalog sections for traceability"

tags:
  - git
  - commits
  - narrative
  - provenance
  - introspection
  - composability

# METHODS

methods:

  COMMIT:
    description: "Create a thoughtful commit with narrative context"
    parameters:
      files:
        type: array
        items: string
        description: "Files to commit (or '.' for all staged)"
      story:
        type: string
        description: "The narrative of what happened and why"
      include_thinking:
        type: boolean
        default: true
        description: "Include reasoning from conversation context"
    returns:
      commit_id: string
      message: string
      thinking_link: string  # Reference to cursor-mirror events
    example: |
      invoke:
        skill: thoughtful-commitment
        method: COMMIT
        parameters:
          files: [characters/animals/cat-terpie/CHARACTER.yml]
          story: "Incarnation Ceremony: Terpie receives emoji soul"
          include_thinking: true

  EXPLAIN:
    description: "Find the thinking that led to an existing commit"
    parameters:
      commit:
        type: string
        description: "Commit hash (full or abbreviated)"
    returns:
      commit_message: string
      timestamp: string
      thinking_blocks: array
      user_request: string
      tool_calls: array
    example: |
      invoke:
        skill: thoughtful-commitment
        method: EXPLAIN
        parameters:
          commit: "abc123"

  NARRATIVE:
    description: "Generate a narrative commit message from context"
    parameters:
      diff_summary:
        type: string
        description: "Summary of changes (or auto-detect from staged)"
      perspective:
        type: string
        enum: [technical, narrative, changelog, detailed]
        default: narrative
    returns:
      message: string
      sections:
        title: string
        body: string
        changes: array
    example: |
      invoke:
        skill: thoughtful-commitment
        method: NARRATIVE
        parameters:
          perspective: narrative

  LINK:
    description: "Link a commit to cursor-mirror events"
    parameters:
      commit:
        type: string
        description: "Commit hash"
      events:
        type: array
        items: string
        description: "Event IDs from cursor-mirror"
    returns:
      linked: boolean
      reference: string

  HISTORY:
    description: "Get narrative history of a file or directory"
    parameters:
      path:
        type: string
        description: "File or directory to trace"
      depth:
        type: integer
        default: 10
        description: "Number of commits to include"
      include_thinking:
        type: boolean
        default: true
    returns:
      timeline: array  # Each entry: commit + message + thinking

  DEEP-COMMIT:
    description: "Technical analytics mining before committing — extract metrics from cursor-mirror"
    note: "Produces quantitative appendix with counts, timestamps, distributions, verification commands"
    
    process:
      # 1. Raw metrics extraction
      - "wc -l transcript — line counts"
      - "grep -c patterns — tool calls, thinking blocks, user turns"
      - "cursor-mirror analyze <composer> — session stats"
      
      # 2. Tool distribution analysis
      - "cursor-mirror tools <composer> — all tool calls"
      - "sort | uniq -c | sort -rn — frequency distribution"
      
      # 3. Thinking block analysis  
      - "grep [Thinking] | measure lengths — min/max/avg/median"
      - "word frequency in thinking — top concepts"
      
      # 4. Activity burst detection
      - "cursor-mirror timeline — extract timestamps"
      - "group by minute — find activity clusters"
      - "detect pauses >60s — find thinking gaps"
      
      # 5. Git commit metrics
      - "git log --numstat — insertions/deletions by file"
      - "git diff --stat — change summary"
      
      # 6. Path analysis
      - "extract all paths from transcript"
      - "group by directory — understand focus areas"
      
      # 7. Generate verification commands
      - "bash one-liners to reproduce each metric"
    
    parameters:
      composer:
        type: string
        description: "Composer ID (or @1 for largest, name fragment, etc)"
      commit_range:
        type: string
        description: "Git commit range for this session (e.g., f21d0d0^..085b94b)"
    
    returns:
      raw_metrics:
        transcript_lines: int
        transcript_bytes: int
        tool_calls: int
        thinking_blocks: int
        user_turns: int
      tool_distribution: object   # {tool_name: count}
      thinking_analysis:
        count: int
        min_chars: int
        max_chars: int
        avg_chars: float
        total_chars: int
      activity_bursts: array      # [{minute: str, events: int}]
      major_pauses: array         # [{from: str, to: str, duration_min: float}]
      commit_metrics:
        files_changed: int
        insertions: int
        deletions: int
        net: int
      files_created: array        # [{path, lines, words, bytes}]
      files_modified: array       # [{path, lines_changed}]
      paths_accessed: array       # unique paths read
      top_thinking_words: array   # [{word, count}]
      verification_commands: str  # bash script to reproduce
    
    example: |
      invoke:
        skill: thoughtful-commitment
        method: DEEP-COMMIT
        parameters:
          composer: "e8587ace"
          commit_range: "f21d0d0^..085b94b"
      
      # Output includes:
      # - Raw metrics table
      # - Tool distribution histogram
      # - Thinking block statistics
      # - Activity burst timeline with ASCII bars
      # - Commit metrics table
      # - Files created/modified tables
      # - Verification bash commands

# COMMIT MESSAGE PROTOCOL

commit_message_protocol:
  format: |
    <title>: <summary> (imperative, <50 chars)
    
    <body>
    Narrative description of what happened and why.
    From whose perspective? What were the motivations?
    What changed emotionally/functionally, not just mechanically?
    
    <changes>
    - Bullet points of mechanical changes
    - For quick scanning
    
    <thinking-ref> (optional)
    Thinking: cursor-mirror://<composer>/<event-range>
    
  perspectives:
    technical: |
      Focus on implementation details, APIs, data structures.
      Good for code changes, refactoring, bug fixes.
      
    narrative: |
      Focus on story, characters, world changes.
      Good for MOOLLM adventures, character evolution.
      
    changelog: |
      Focus on user-facing changes, features, fixes.
      Good for release notes, version history.
      
    detailed: |
      Everything: technical + narrative + reasoning.
      Good for significant changes, debugging archaeology.

  examples:
    narrative: |
      Incarnation Ceremony: Kittens receive emoji souls
      
      The Cat Cave family gathered for the Public Incarnation Ceremony.
      Each kitten's terpene essence was captured in 5 emojis.
      Pronouns were self-chosen. The gong rang thrice.
      
      - Added emoji_identity to all 8 kittens
      - Added pronouns (she/her, self-chosen)
      - Added memories: incarnation_ceremony
      - Updated Cat Cave README with Emoji Soul Registry
      
      Thinking: cursor-mirror://abc123/events/140-148
      
    technical: |
      fix(auth): Resolve race condition in session validation
      
      The session cookie was being checked before the token refresh
      completed, causing intermittent logouts. Added await to ensure
      refresh completes before validation.
      
      - Modified auth/session.ts: await refreshToken()
      - Added test: session.test.ts - race condition scenario
      - Updated timeout from 5s to 10s for slow networks
      
    changelog: |
      feat: Add dark mode toggle to settings
      
      Users can now switch between light and dark themes.
      Preference is saved to localStorage and respected on reload.
      
      - New: Settings > Appearance > Theme toggle
      - New: System preference detection (prefers-color-scheme)
      - Fixed: Contrast issues in sidebar with dark backgrounds

# CURSOR-MIRROR INTEGRATION — The Reflection Engine

cursor_mirror_capabilities:
  description: "cursor-mirror is a 59-command introspection toolkit for Cursor IDE"
  
  data_sources:
    sqlite_databases:
      - "~/Library/Application Support/Cursor/User/workspaceStorage/*/state.vscdb"
      - "Contains: bubbles (messages), composers (chats), context, tools"
    plaintext_transcripts:
      - "~/.cursor/projects/*/agent-transcripts/*.txt"
      - "Contains: full conversation with [Thinking], [Tool call], [Tool result] markers"
    ai_tracking:
      - "~/.cursor/ai-*.jsonl"
      - "Contains: AI code attribution, model usage"
  
  navigation_commands:
    - "tree                    # Hierarchical workspace/composer browser"
    - "tree w9.c2              # Drill into workspace 9, composer 2"
    - "find <pattern>          # Search by name across all data"
    - "which <ref>             # Resolve any reference to full details"
    - "tail --limit 50         # Recent messages across all chats"
  
  viewing_commands:
    - "timeline <ref>          # Chronological event stream"
    - "thinking <ref>          # Extract reasoning blocks"
    - "tools <ref>             # All tool calls with args"
    - "transcript <ref>        # Full readable conversation"
    - "agent-transcript <ref>  # Raw plaintext transcript"
  
  analysis_commands:
    - "analyze <ref>           # Deep stats: tools, models, duration"
    - "tgrep <pattern>         # Regex search across transcripts"
    - "context-sources <ref>   # What files/code was gathered"
    - "searches <ref>          # Codebase/web search queries"
  
  database_access:
    - "sql --db <ref> 'query'  # Run SQL directly"
    - "dbs                     # List all databases"
    - "tables --db <ref>       # Show tables"
    - "keys                    # List ItemTable keys"
  
  output_formats:
    - "text (default), json, jsonl, yaml, csv, md"
    - "Use -f json for programmatic processing"

# GIT INTEGRATION

git_integration:
  description: "Git as the universal substrate for state and history"
  commands:
    status: "git status --short"
    diff: "git diff --stat / --numstat"
    log: "git log --oneline / --format='%H %s'"
    show: "git show --stat <commit>"
    blame: "git blame <file>"
    commit: "git commit -m '$(cat <<EOF ... EOF)'"

# SHELL INTEGRATION — Data Processing Pipeline

shell_patterns:
  counting:
    - "wc -l file                    # Line count"
    - "wc -c file                    # Byte count"
    - "grep -c 'pattern' file        # Match count"
  
  frequency_analysis:
    - "sort | uniq -c | sort -rn     # Histogram"
    - "cut -d' ' -f1 | sort | uniq -c"
  
  text_extraction:
    - "grep 'pattern' file           # Filter lines"
    - "grep -o 'pattern' file        # Extract matches only"
    - "sed 's/old/new/' file         # Transform"
    - "awk '{print $1, $3}'          # Select columns"
  
  aggregation:
    - "awk '{sum+=$1} END{print sum}'"
    - "awk 'NR==1{min=max=$1} {if($1<min)min=$1; if($1>max)max=$1} END{print min,max}'"
  
  python_inline:
    - "python3 -c 'import json,sys; data=json.load(sys.stdin); ...'"
    - "python3 -c 'from collections import Counter; ...'"

# AUTOMATION

automation:
  pre_commit_hook:
    description: "Optionally validate commit messages"
    checks:
      - "Title exists and is <50 chars"
      - "Body provides context (not just 'updated file')"
      - "Changes are listed"
    
  post_commit_hook:
    description: "Optionally link to cursor-mirror after commit"
    actions:
      - "Extract commit hash"
      - "Find recent cursor-mirror events"
      - "Store link in .moollm/commit-links.yml"
