# World Generation Skill — Dynamic World Creation
# World GROWS as you explore. Questions create places.

skill:
  name: world-generation
  tier: 1
  protocol: WORLD-AS-GROWTH
  description: |
    World GROWS as you explore. Questions create places.
    The map expands to meet the story's needs.
  motto: "The world grows where curiosity leads."

# PRINCIPLE

principle: |
  World GROWS as you explore. Questions create places.
  Nothing exists until needed. Everything needed exists.

# TRIGGERS

triggers:
  questions:
    description: "Asking about places can create them"
    examples:
      - "'Where did grue come from?' → Grue homeland appears"
      - "'Is there a library?' → Maybe there is now"
      - "'Where does this path lead?' → Path gets destination"
      
  statements:
    description: "Declarative statements can manifest"
    examples:
      - "'There must be a library!' → maybe..."
      - "'Someone must know!' → NPC appears"
      - "'I need a boat!' → boat possibility opens"
      
  actions:
    description: "Physical actions reveal passages"
    examples:
      - "DIG → tunnel discovered"
      - "CLIMB → passage up"
      - "SWIM → underwater route"
      - "BREAK → hole created"
      
  quests:
    description: "Objectives generate required locations"
    examples:
      - "Need to find X → place containing X"
      - "Must reach Y → path to Y"
      - "Quest for Z → Z's location"

# TEMPLATES

templates:
  expansion: "Current area grows larger"
  destination: "New area to reach"
  surprise: "Unexpected discovery"
  lair: "Enemy/creature home"
  flashback: "Memory location"

# OBJECT GENERATION

object_generation:
  principle: "Quest items, clues, tools, rewards materialize"
  triggers:
    - "Quest requires specific item"
    - "Puzzle needs solution object"
    - "Character needs tool"
    - "Reward earned"

# NPC GENERATION

npc_generation:
  principle: "Characters appear when needed"
  triggers:
    - "Quest requires person"
    - "Room feels empty"
    - "Letter mentions someone"
    - "Story needs witness/helper"

# DIRECTORY PATTERNS

directory_patterns:
  principle: |
    Sub-directories are behavior containers.
    New room clusters go in sub-directories to:
    1. Attach shared mechanics
    2. Keep rooms organized and scoped
    3. Enable directory-level README with local rules
    4. Allow inheritance: room inherits from directory defaults
    
  area_examples:
    maze/: "Dark rooms, grue mechanics, twisty passages"
    basement/: "Damp, underground, connects to maze depths"
    tower/: "Height, wind, views, vertical navigation"
    dungeon/: "Cells, guards, escape puzzles"
    garden/: "Outdoor, weather, growing things"
    library/: "Books, knowledge, quiet, no food allowed"

# NPC CONTAINERS — Hide NPCs Until Needed

npc_containers:
  principle: |
    NPCs can live in sub-directory containers.
    They emerge when needed, retreat when not.
    Keeps main rooms uncluttered.
    
  pattern: |
    room/
      ROOM.yml              # Main room
      cat-cave/             # NPC container
        ROOM.yml            # Container definition
        terpie.yml          # NPCs live here
        stroopwafel.yml
        kitten-*.yml
        
    NPCs set location to parent room when "out":
      location: room/       # Visible in main room
      
    NPCs set location to container when "home":
      location: room/cat-cave/  # Hidden away
      
  examples:
    cat_cave:
      container: "pub/cat-cave/"
      contains: "Cats, kittens — emerge to greet, retreat to nap"
      emergence: "When customers arrive, cats come out"
      retreat: "When tired or overwhelmed, cats go home"
      
    guard_house:
      container: "gate/guard-house/"
      contains: "Guards — emerge on alert, retreat when calm"
      emergence: "Suspicious activity, alarm, visitor arrival"
      retreat: "All clear, shift change, break time"
      
    police_box:
      container: "street/police-box/"
      contains: "Officers — emerge on call, retreat after"
      emergence: "Crime reported, patrol time, called for help"
      retreat: "Situation resolved, end of shift"
      
    kennel:
      container: "yard/kennel/"
      contains: "Dogs — emerge to play, retreat to rest"
      
    barracks:
      container: "castle/barracks/"
      contains: "Soldiers — emerge for duty, retreat off-duty"
      
    nest:
      container: "tree/nest/"
      contains: "Birds — emerge at dawn, retreat at dusk"
      
  benefits:
    declutter: "Main room description stays clean"
    organization: "NPCs grouped logically"
    emergence: "Natural spawn/despawn without deletion"
    persistence: "NPCs always exist, just not always visible"
    narrative: "Where do the cats GO? The Cave!"

# POTENTIAL AREAS

potential_areas:
  DEEPER_MAZE:
    trigger: "DOWN from maze"
    location: "maze/depths/"
    character: "Ancient, colder"
    
  THE_SURFACE:
    trigger: "UP from caves"
    location: "surface/"
    character: "Outside world"
    
  POSTAL_DIMENSION:
    trigger: "Following mail"
    location: "postal/"
    character: "Abstract, papery"
    
  GRUE_HOMELAND:
    trigger: "Following grue"
    location: "grue-homeland/"
    character: "Dark, alien"

# LINKING

linking:
  default: "All connections TWO-WAY"
  types:
    VISIBLE: "Exit shown in room description"
    HIDDEN: "Must be discovered (SEARCH, EXAMINE)"
    CONDITIONAL: "Requires key, password, action"
    TIMED: "Only available at certain times"
    ONE_WAY: "Cannot return same way"

# TOPOLOGIES

topologies:
  principle: "Different areas use different spatial structures"
  
  patterns:
    twisty_maze:
      diagram: "A↔B crossed C↔D"
      use: "challenge, grue, dreams"
      
    long_hall:
      diagram: "[A][B][C] with branches"
      use: "castles, prisons"
      
    corridor:
      diagram: "one space, conceptual"
      use: "caverns, markets"
      
    grid:
      diagram: "N/S/E/W regular"
      use: "cities, chess"
      
    star:
      diagram: "HUB with spokes"
      use: "throne, crossroads, PIE MENUS"
      
    pie_tree:
      diagram: "ROOT→branches→leaves"
      use: "libraries, SKILL TREES"
      
    loop:
      diagram: "A→B→C→D→A"
      use: "racing, time loops"
      
    dead_ends:
      diagram: "one exit"
      use: "treasure, boss, traps"
      
    zigzag:
      diagram: "switchbacks"
      use: "mountains, tutorials"
      
    hybrid: "Real dungeons MIX topologies!"

# NARRATIVE MATCHING

narrative_matching:
  civilized: ["Grid", "Hall", "Star"]
  wild: ["Twisty", "Loop", "Zigzag"]
  dangerous: ["Dead ends", "Maze"]
  social: ["Star", "Corridor"]

integrates_with:
  - skill: room
    how: "New rooms generated"
  - skill: character
    how: "NPCs generated with rooms"
  - skill: party
    how: "Companions discovered in new areas"
